name: robot-env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - brotlicffi=1.0.9.2=py39h50f4ffc_2
  - bullet-cpp=3.25=py39hbc50386_4
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2025.10.5=py39hca03da5_0
  - cffi=2.0.0=py39h3a083c1_0
  - charset-normalizer=3.4.4=py39hca03da5_0
  - expat=2.7.1=h313beb8_0
  - filelock=3.17.0=py39hca03da5_0
  - freetype=2.13.3=h47d26ad_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py39h5c1b81f_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=py39hca03da5_0
  - jinja2=3.1.6=py39hca03da5_0
  - jpeg=9f=h2f69dba_0
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=h313beb8_0
  - libblas=3.9.0=38_h51639a9_openblas
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - liblapack=3.9.0=38_hd9741b5_openblas
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.50=h5c318fc_0
  - libsqlite=3.50.4=h4237e3c_0
  - libtiff=4.7.0=h91aec0a_0
  - libwebp-base=1.3.2=h80987f9_1
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.4=h4a912ad_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py39h80987f9_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py39hca03da5_0
  - ncurses=6.5=hee39554_0
  - networkx=3.2.1=py39hca03da5_0
  - numpy=1.21.1=py39h96f19d2_1
  - openjpeg=2.5.4=h959fc53_1
  - openssl=3.5.4=h5503f6c_0
  - pillow=11.1.0=py39h41ba818_1
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.4=hd74edd7_1002
  - pybullet=3.25=py39he24f47d_4
  - pycparser=2.23=py39hca03da5_0
  - pysocks=1.7.1=py39hca03da5_1
  - python=3.9.20=h9e33284_1_cpython
  - python_abi=3.9=8_cp39
  - pytorch=2.2.2=py3.9_0
  - pyyaml=6.0.2=py39h80987f9_0
  - readline=8.3=h0b18652_0
  - requests=2.32.5=py39hca03da5_0
  - setuptools=80.9.0=py39hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - sympy=1.14.0=py39hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - torchvision=0.17.2=py39_cpu
  - typing_extensions=4.15.0=py39hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py39hca03da5_0
  - wheel=0.45.1=py39hca03da5_0
  - xorg-libx11=1.8.12=h6a5fb8c_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xorg-libxext=1.3.6=hd74edd7_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - exceptiongroup==1.3.0
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - importlib-resources==6.5.2
      - kiwisolver==1.4.7
      - matplotlib==3.9.4
      - ollama==0.6.0
      - opencv-python==4.12.0.88
      - packaging==25.0
      - polars==1.35.1
      - polars-runtime-32==1.35.1
      - psutil==7.1.3
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - scipy==1.13.1
      - six==1.17.0
      - sniffio==1.3.1
      - typing-inspection==0.4.2
      - ultralytics==8.3.225
      - ultralytics-thop==2.0.18
      - zipp==3.23.0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/robot-env
